### ISSUE TITLE
Is ssl work?

### ISSUE THREAD

**Issue by behroozbc** [SeppPenner/NetCoreMQTTExampleIdentityConfig#6]
Hi 
I want to know this method you add SSL Work in asp.net ? 
https://github.com/SeppPenner/NetCoreMQTTExampleIdentityConfig/blob/85c413e38b1ac03f70259426f6a1c6238d8e8d4e/src/NetCoreMQTTExampleIdentityConfig/Startup.cs#L184

**Comment by SeppPenner** [comment]
This is the code that adds SSL support with a custom certificate, yes:

```csharp
.WithEncryptedEndpoint().WithEncryptedEndpointPort(mqttSettings.Port)
                    .WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx))
                    .WithEncryptionSslProtocol(SslProtocols.Tls12)
```

**Comment by SeppPenner** [comment]
I assume that this is answered and fixed?
